### ISSUE TITLE
Small enhancement ideas

### ISSUE THREAD

**Issue by emhl** [paramt/deathmatch#8]
I think your plugin is very neat, but only has limited functionality/use. I got a few ideas, that coulld improve the Plugin in my opinion:

- Ability to turn off the Deathmatch Mode 
- maybe clearing the inventory after the round instead of in the beginning of the round (or with extra command) -> allows for combination with other game modes.
- Ability to change the worldborder size in the beginning of a round.
- timer to automatically start deatmatch mode

**Comment by paramt** [comment]
Those are some great suggestions! I've stopped working on the project, but if you'd like to you can create a PR and I'll merge it
